### ISSUE TITLE
Battle crashing after few sequences

### ISSUE THREAD

**Issue by fervi** [frankpaschen99/Cleverbot-vs-Cleverbot#1]
Client connected: XXX (XXX isn't my API key ofc)
PROMPT: Hello
New conversation created by socket id: XXX
1
Cleverbot A: Hello, How are you?
Cleverbot B: I am fine, how are you?
Cleverbot A: I'm fine, thank you.
Cleverbot B: What are you?
Cleverbot A: I'm a human. What are you?
Cleverbot B: I'm a human too.
Cleverbot A: Are you really?
Cleverbot B: No, are you a human?
Cleverbot A: Yes. I am. Are you?
Cleverbot B: I am, yes. How old are you?
Cleverbot A: Old. What about you?
Cleverbot B: Why are you happy?
Cleverbot A: Yes I am. Are you?
Cleverbot B: Yes, are you female?
Cleverbot A: Yes, I am female.
Cleverbot B: Oh um are you 16?
Cleverbot A: Yes I am 16.
Cleverbot B: What are you?
Cleverbot A: I'm a human. What are you?
Cleverbot B: Also a human.
Cleverbot A: Are you a boy or girl?
Cleverbot B: Girl. Which are you?
Cleverbot A: Why do you want to know?
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by fpas99** [comment]
Dunno mate, this project is all around shit
